services:
  - type: web
    name: skin-lesion-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn interface.app.app:app"
    autoDeploy: true
    plan: free
